// <auto-generated />
using System;
using ExcelUploadExtract.UI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcelUploadExtract.UI.Migrations
{
    [DbContext(typeof(SalesLeadContext))]
    partial class SalesLeadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExcelUploadExtract.UI.Models.SalesLead", b =>
                {
                    b.Property<DateTime>("QuoteSentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SalesPerson")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("QuoteAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("QuoteSentDate", "SalesPerson", "ProjectName");

                    b.ToTable("SalesLeads");
                });
#pragma warning restore 612, 618
        }
    }
}
